[project]
name = "uniconnect-api"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi==0.128.0",
  "uvicorn[standard]==0.40.0",
  "sqlalchemy==2.0.46",
  "psycopg[binary]==3.3.2",
  "pydantic==2.12.5",
  "pydantic-settings==2.12.0",
  "python-dotenv==1.2.1",
  "email-validator==2.3.0",
  "alembic==1.18.1",
  "argon2-cffi==25.1.0",
  "PyJWT==2.10.1",
  "python-multipart==0.0.20",
  "httpx==0.28.1",
  "slowapi==0.1.9",
]

[tool.vercel]
entrypoint = "app.main:app"
